# Generated by Django 5.2 on 2025-09-01 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(default="Argenis Manzanares", max_length=200),
                ),
                (
                    "tagline",
                    models.CharField(default="Desarrollador Backend en Python", max_length=300),
                ),
                (
                    "about_me",
                    models.TextField(
                        default="Soy programador web backend con experiencia en Python, Django, FastAPI, Flask, SQL y Docker. Estoy enfocado en crear APIs y sistemas escalables."
                    ),
                ),
                (
                    "email",
                    models.EmailField(default="argenis010@gmail.com", max_length=254),
                ),
                (
                    "github_username",
                    models.CharField(default="Kallheset", max_length=100),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        default="https://www.linkedin.com/in/argenis-manzanares-108b4a349/"
                    ),
                ),
                (
                    "cv_file_path",
                    models.CharField(
                        default="cv/Argenis_Manzanares_CV.pdf",
                        help_text="Ruta relativa desde static/",
                        max_length=200,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Portfolio Settings",
                "verbose_name_plural": "Portfolio Settings",
            },
        ),
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Color hex para la categoría",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "icon_url",
                    models.URLField(help_text="URL del icono (ej: devicon CDN)"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("language", "Lenguaje de Programación"),
                            ("framework", "Framework"),
                            ("database", "Base de Datos"),
                            ("tool", "Herramienta"),
                            ("cloud", "Cloud/DevOps"),
                        ],
                        default="tool",
                        max_length=50,
                    ),
                ),
                (
                    "proficiency_level",
                    models.IntegerField(
                        choices=[
                            (1, "Básico"),
                            (2, "Intermedio"),
                            (3, "Avanzado"),
                            (4, "Experto"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=True, help_text="Mostrar en el portfolio"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, help_text="Orden de visualización"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "detailed_description",
                    models.TextField(blank=True, help_text="Descripción detallada opcional"),
                ),
                ("github_url", models.URLField(blank=True, null=True)),
                ("demo_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("completed", "Completado"),
                            ("archived", "Archivado"),
                            ("in_progress", "En Desarrollo"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=True, help_text="Mostrar en el portfolio"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, help_text="Orden de visualización"),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.projectcategory",
                    ),
                ),
                (
                    "technologies",
                    models.ManyToManyField(
                        blank=True, help_text="Tecnologías utilizadas", to="core.skill"
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company_or_institution", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField()),
                (
                    "experience_type",
                    models.CharField(
                        choices=[
                            ("work", "Experiencia Laboral"),
                            ("education", "Educación"),
                            ("certification", "Certificación"),
                            ("volunteer", "Voluntariado"),
                        ],
                        default="work",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(blank=True, help_text="Dejar vacío si es actual", null=True),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, help_text="¿Es el trabajo/estudio actual?"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=True, help_text="Mostrar en el portfolio"),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("technologies", models.ManyToManyField(blank=True, to="core.skill")),
            ],
            options={
                "verbose_name_plural": "Experiences",
                "ordering": ["display_order", "-start_date"],
            },
        ),
    ]
