# Generated by Django 5.2.5 on 2025-09-15 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Mensaje de Contacto",
                "verbose_name_plural": "Mensajes de Contacto",
            },
        ),
        migrations.AlterModelOptions(
            name="experience",
            options={
                "ordering": ["display_order", "-start_date"],
                "verbose_name": "Experiencia",
                "verbose_name_plural": "Experiencias",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["display_order", "-created_at"],
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
            },
        ),
        migrations.AlterModelOptions(
            name="projectcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Categoría de Proyecto",
                "verbose_name_plural": "Categorías de Proyecto",
            },
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={
                "ordering": ["display_order", "name"],
                "verbose_name": "Habilidad",
                "verbose_name_plural": "Habilidades",
            },
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="admin_notes",
            field=models.TextField(
                blank=True, help_text="Notas internas del administrador"
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="replied_at",
            field=models.DateTimeField(
                blank=True, help_text="Fecha en que se respondió", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="featured_image",
            field=models.URLField(
                blank=True, help_text="URL de imagen destacada del proyecto", null=True
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="years_experience",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Años de experiencia con esta tecnología",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectcategory",
            name="color",
            field=models.CharField(
                default="#3B82F6",
                help_text="Color hex para la categoría",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Debe ser un color hex válido (ej: #3B82F6)",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="proficiency_level",
            field=models.IntegerField(
                choices=[
                    (1, "Básico"),
                    (2, "Intermedio"),
                    (3, "Avanzado"),
                    (4, "Experto"),
                ],
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="experience",
            index=models.Index(
                fields=["is_featured"], name="core_experi_is_feat_53cc41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="experience",
            index=models.Index(
                fields=["experience_type"], name="core_experi_experie_e2c0d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="experience",
            index=models.Index(
                fields=["is_current"], name="core_experi_is_curr_de8139_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_featured"], name="core_projec_is_feat_e41834_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status"], name="core_projec_status_2020cc_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["category"], name="core_projec_categor_55bb7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["display_order"], name="core_projec_display_3a3e0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["is_featured"], name="core_skill_is_feat_71a261_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["category"], name="core_skill_categor_881ec3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["display_order"], name="core_skill_display_69a162_idx"
            ),
        ),
    ]
